CREATE TABLE IF NOT EXISTS User
(
	Id 		 int  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	Username text UNIQUE NOT NULL,
	Email    text UNIQUE NOT NULL,
	Password text NOT NULL,
	
	CONSTRAINT username_length CHECK (
		length(Username) >= 4 AND
		length(Username) <= 28
	)
);