DROP TABLE IF EXISTS user_account_state;

CREATE TABLE user_account_state 
(
	id 				int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
	user_account_id int NOT NULL,
	
	is_email_validated bool NOT NULL GENERATED BY DEFAULT AS false,
	
	CONSTRAINT user_id_fk
		FOREIGN KEY(user_id)
		REFERENCES user_account(id),
);
